# -*- coding: utf-8 -*-
"""GNSS/INS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_EMpBQUdWI7Fdt1VOa1OhSv7iVfKBUzr
"""

import numpy as np
import matplotlib.pyplot as plt

# --- 1. EKF SINIFI (GNSS/INS ENTEGRASYONU) ---
class EKF_GNSS_INS:
    def __init__(self, dt, std_acc, std_yaw_rate, std_gps):
        self.dt = dt
        self.x = np.zeros((4, 1)) # [x, y, v, theta]
        self.P = np.eye(4)        # Kovaryans
        self.Q = np.diag([0, 0, std_acc**2, std_yaw_rate**2]) # İşlem Gürültüsü
        self.R = np.diag([std_gps**2, std_gps**2])            # Ölçüm Gürültüsü
        self.H = np.array([[1, 0, 0, 0], [0, 1, 0, 0]])       # Ölçüm Matrisi
        self.I = np.eye(4)

    def predict(self, u):
        theta = self.x[3, 0]
        v = self.x[2, 0]
        a = u[0]
        omega = u[1]
        dt = self.dt

        # Hareket Modeli
        new_x = self.x[0, 0] + v * np.cos(theta) * dt
        new_y = self.x[1, 0] + v * np.sin(theta) * dt
        new_v = v + a * dt
        new_theta = theta + omega * dt
        self.x = np.array([[new_x], [new_y], [new_v], [new_theta]])

        # Jakobiyen (F)
        F = np.eye(4)
        F[0, 3] = -v * np.sin(theta) * dt
        F[0, 2] = np.cos(theta) * dt
        F[1, 3] = v * np.cos(theta) * dt
        F[1, 2] = np.sin(theta) * dt

        # Q Gürültüsünü Duruma Yayma
        Q_noise = np.diag([0.1 * dt**2, 0.1 * dt**2, self.Q[2, 2] * dt**2, self.Q[3, 3] * dt**2])
        self.P = F @ self.P @ F.T + Q_noise

    def update(self, z):
        z_pred = self.H @ self.x
        y = z - z_pred
        S = self.H @ self.P @ self.H.T + self.R
        K = self.P @ self.H.T @ np.linalg.inv(S)
        self.x = self.x + K @ y
        self.P = (self.I - K @ self.H) @ self.P

# --- 2. SİMÜLASYON VE VERİ TOPLAMA ---

# Ayarlar
DT = 0.1
TIME = 30.0
STEPS = int(TIME / DT)

# Filtre Başlatma
ekf = EKF_GNSS_INS(dt=DT, std_acc=0.2, std_yaw_rate=0.1, std_gps=1.5)

# Gerçek Durum (Ground Truth)
true_state = np.zeros((4, 1))
u_true = np.array([1.0, 0.1]) # Sabit ivme ve dönüş

# Veri Saklama Listeleri
true_path = []
est_path = []
gps_measurements = []

# Analiz Listeleri
innovation_history = []
sigma_history = []
error_history = []

print("Simülasyon çalışıyor...")

for i in range(STEPS):
    # A. Gerçek Dünyayı Hareket Ettir
    v = true_state[2, 0]
    theta = true_state[3, 0]
    true_state[0, 0] += v * np.cos(theta) * DT
    true_state[1, 0] += v * np.sin(theta) * DT
    true_state[2, 0] += u_true[0] * DT
    true_state[3, 0] += u_true[1] * DT
    true_path.append(true_state[:2].flatten())

    # B. Sensör Verisi Üret (Gürültü Ekle)
    u_noisy = u_true + np.random.normal(0, [0.2, 0.1])
    gps_reading = true_state[:2] + np.random.normal(0, 1.5, (2, 1))

    # C. EKF ADIMLARI

    # 1. Predict (Her döngüde)
    ekf.predict(u_noisy)

    # 2. Update (Sadece GPS geldiğinde - örn: her 10 adımda bir)
    if i % 10 == 0:
        # İnovasyonu (Residual) hesapla ve kaydet
        z_pred = ekf.H @ ekf.x
        residual = gps_reading - z_pred
        innovation_history.append(residual.flatten())

        # Filtreyi güncelle
        ekf.update(gps_reading)
        gps_measurements.append(gps_reading.flatten())
    else:
        # GPS yoksa inovasyon verisine boş (NaN) değer at
        innovation_history.append([np.nan, np.nan])

    # D. Veri Kaydı (Her adımda)
    est_path.append(ekf.x[:2].flatten())

    # Sigma (Belirsizlik) Kaydı (P matrisinin köşegeninin karekökü)
    std_x = np.sqrt(ekf.P[0, 0])
    std_y = np.sqrt(ekf.P[1, 1])
    sigma_history.append([std_x, std_y])

    # Gerçek Hata Kaydı (True - Estimated)
    err_x = true_state[0, 0] - ekf.x[0, 0]
    err_y = true_state[1, 0] - ekf.x[1, 0]
    error_history.append([err_x, err_y])

# --- 3. GÖRSELLEŞTİRME VE ANALİZ ---

true_path = np.array(true_path)
est_path = np.array(est_path)
gps_measurements = np.array(gps_measurements)
innovation_history = np.array(innovation_history)
sigma_history = np.array(sigma_history)
error_history = np.array(error_history)
time_axis = np.arange(STEPS) * DT

# Grafik 1: Rota
plt.figure(figsize=(10, 6))
plt.plot(true_path[:, 0], true_path[:, 1], 'g-', label='Gerçek Rota')
plt.scatter(gps_measurements[:, 0], gps_measurements[:, 1], c='r', marker='x', alpha=0.5, label='GPS Ölçümü')
plt.plot(est_path[:, 0], est_path[:, 1], 'b-', linewidth=2, label='EKF Sonucu')
plt.title('GNSS/INS Entegrasyon Sonucu')
plt.legend()
plt.grid()

# Grafik 2: 3-Sigma Tutarlılık Testi (X Ekseni)
plt.figure(figsize=(10, 5))
plt.plot(time_axis, error_history[:, 0], 'k-', label='Gerçek Hata (X)')
plt.plot(time_axis, 3 * sigma_history[:, 0], 'r--', label='+3 Sigma Sınırı')
plt.plot(time_axis, -3 * sigma_history[:, 0], 'r--', label='-3 Sigma Sınırı')
plt.title('Tutarlılık Testi (Consistency Check) - X Ekseni')
plt.xlabel('Zaman (s)')
plt.ylabel('Hata (m)')
plt.legend()
plt.grid()

# Grafik 3: İnovasyon Analizi
plt.figure(figsize=(10, 5))
plt.plot(time_axis, innovation_history[:, 0], 'b.', markersize=5, label='İnovasyon X')
plt.axhline(0, color='k', linestyle='--')
plt.title('İnovasyon (Residual) Analizi')
plt.xlabel('Zaman (s)')
plt.ylabel('Fark (m)')
plt.legend()
plt.grid()

plt.show()

# İstatistikler
rmse_x = np.sqrt(np.mean(error_history[:, 0]**2))
print(f"X Ekseni RMSE Hatası: {rmse_x:.3f} metre")

import numpy as np
import matplotlib.pyplot as plt

# Matrislerin konsolda düzgün görünmesi için ayar (Bilimsel gösterimi kapatır, virgülden sonra 3 hane)
np.set_printoptions(precision=3, suppress=True, linewidth=120)

class EKF_GNSS_INS:
    def __init__(self, dt, std_acc, std_yaw_rate, std_gps):
        self.dt = dt
        self.x = np.zeros((4, 1)) # [x, y, v, theta]
        self.P = np.eye(4)        # Kovaryans
        self.Q = np.diag([0, 0, std_acc**2, std_yaw_rate**2]) # İşlem Gürültüsü
        self.R = np.diag([std_gps**2, std_gps**2])            # Ölçüm Gürültüsü
        self.H = np.array([[1, 0, 0, 0], [0, 1, 0, 0]])       # Ölçüm Matrisi
        self.I = np.eye(4)

    def predict(self, u, debug=False):
        theta = self.x[3, 0]
        v = self.x[2, 0]
        a = u[0]
        omega = u[1]
        dt = self.dt

        # --- DEBUG BAŞLANGIÇ ---
        if debug:
            print("\n" + "="*40)
            print(">>> ADIM 1: PREDICT (TAHMİN)")
            print(f"Eski Durum (x):\n{self.x.T}")
            print(f"Girdi (u) [ivme, dönüş]: {u}")
        # -----------------------

        # Hareket Modeli
        new_x = self.x[0, 0] + v * np.cos(theta) * dt
        new_y = self.x[1, 0] + v * np.sin(theta) * dt
        new_v = v + a * dt
        new_theta = theta + omega * dt
        self.x = np.array([[new_x], [new_y], [new_v], [new_theta]])

        # Jakobiyen (F)
        F = np.eye(4)
        F[0, 3] = -v * np.sin(theta) * dt
        F[0, 2] = np.cos(theta) * dt
        F[1, 3] = v * np.cos(theta) * dt
        F[1, 2] = np.sin(theta) * dt

        # Q Gürültüsünü Duruma Yayma
        Q_noise = np.diag([0.1 * dt**2, 0.1 * dt**2, self.Q[2, 2] * dt**2, self.Q[3, 3] * dt**2])
        self.P = F @ self.P @ F.T + Q_noise

        # --- DEBUG SONU ---
        if debug:
            print(f"F Matrisi (Jakobiyen):\n{F}")
            print(f"Yeni Tahmin (x_pred):\n{self.x.T}")
            print(f"Tahmin Kovaryansı (P_pred) [Köşegenler artmalı]:\n{self.P}")
            print("="*40 + "\n")

    def update(self, z, debug=False):
        # --- DEBUG BAŞLANGIÇ ---
        if debug:
            print("\n" + "*"*40)
            print(">>> ADIM 2: UPDATE (DÜZELTME)")
            print(f"Gelen GPS Ölçümü (z):\n{z.T}")
        # -----------------------

        z_pred = self.H @ self.x
        y = z - z_pred # İnovasyon

        S = self.H @ self.P @ self.H.T + self.R
        K = self.P @ self.H.T @ np.linalg.inv(S) # Kalman Kazancı

        self.x = self.x + K @ y
        self.P = (self.I - K @ self.H) @ self.P

        # --- DEBUG SONU ---
        if debug:
            print(f"İnovasyon (y) [GPS - Tahmin]:\n{y.T}")
            print(f"Kalman Kazancı (K) [Büyüdükçe GPS'e güvenir]:\n{K}")
            print(f"Düzeltilmiş Durum (x_final):\n{self.x.T}")
            print(f"Düzeltilmiş Kovaryans (P_final) [Azalmalı]:\n{self.P}")
            print("*"*40 + "\n")

# --- SİMÜLASYON AYARLARI ---
DT = 0.1
STEPS = 50 # Örnek için adımı kısalttım (normalde 300)

ekf = EKF_GNSS_INS(dt=DT, std_acc=0.2, std_yaw_rate=0.1, std_gps=1.5)
true_state = np.zeros((4, 1))
u_true = np.array([1.0, 0.1])

print("Simülasyon başladı. Sadece 10. adımda matrisleri basacağız...")

for i in range(STEPS):
    # Simülasyon Verisi Üretimi
    v = true_state[2, 0]
    theta = true_state[3, 0]
    true_state[0, 0] += v * np.cos(theta) * DT
    true_state[1, 0] += v * np.sin(theta) * DT
    true_state[2, 0] += u_true[0] * DT
    true_state[3, 0] += u_true[1] * DT

    u_noisy = u_true + np.random.normal(0, [0.2, 0.1])
    gps_reading = true_state[:2] + np.random.normal(0, 1.5, (2, 1))

    # --- KONTROLLÜ BASKI (Sadece i = 10 olduğunda detayları göster) ---
    # Eğer tüm adımları görmek istersen "if True:" yapabilirsin.
    enable_debug = (i == 10)

    if enable_debug:
        print(f"\n--- SİMÜLASYON ADIMI: {i} ---")

    # 1. PREDICT
    ekf.predict(u_noisy, debug=enable_debug)

    # 2. UPDATE (Sadece 10. adımda ve mod 10'da çalışır)
    if i % 10 == 0:
        ekf.update(gps_reading, debug=enable_debug)

print("Tamamlandı.")

import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import io

# --- 1. DOSYA YÜKLEME ADIMI ---
print("Lütfen .log dosyasını seçin (Aşağıdaki butona tıkla):")
uploaded = files.upload()

# Yüklenen dosyanın ismini otomatik al
filename = next(iter(uploaded))
print(f"\n'{filename}' dosyası başarıyla yüklendi, analiz başlıyor...")

# --- 2. EKF SINIFI (Matematiksel Model) ---
class EKF_GNSS_INS:
    def __init__(self, dt, std_acc, std_yaw_rate, std_gps):
        self.dt = dt
        self.x = np.zeros((4, 1)) # [x, y, v, theta]               #Robotun durumunu tutar (Konum X, Konum Y, Hız, Yön). Başlangıçta hepsi 0.
        self.P = np.eye(4)                                         #Güven matrisi. Köşegen birim matristir. Başlangıçta "neredeyim pek emin değilim" der.
        self.Q = np.diag([0, 0, std_acc**2, std_yaw_rate**2])      #Sistem Gürültüsü. İvmeölçer ve jiroskopa ne kadar güvenmediğimizi tanımlarız.
        self.R = np.diag([std_gps**2, std_gps**2])                 #Ölçüm Gürültüsü. GPS'e ne kadar güvenmediğimizi tanımlarız (Örn: 3 metre hata yapabilir).
        self.H = np.array([[1, 0, 0, 0], [0, 1, 0, 0]])
        self.I = np.eye(4)

    def predict(self, u):       #(Tahmin Et - IMU ile)
        theta = self.x[3, 0]
        v = self.x[2, 0]
        a = u[0]
        omega = u[1]
        dt = self.dt

        # Hareket Modeli Eski konuma, hız x zaman eklenir. Hıza, ivme x zaman eklenir. Açıya, dönüş hızı x zaman eklenir.
        new_x = self.x[0, 0] + v * np.cos(theta) * dt
        new_y = self.x[1, 0] + v * np.sin(theta) * dt
        new_v = v + a * dt
        new_theta = theta + omega * dt
        self.x = np.array([[new_x], [new_y], [new_v], [new_theta]])

        # Jakobiyen Hareket doğrusal olmadığı için (sinüs/kosinüs var), matrisleri güncellemek için türev alırız.
        F = np.eye(4)
        F[0, 3] = -v * np.sin(theta) * dt
        F[0, 2] = np.cos(theta) * dt
        F[1, 3] = v * np.cos(theta) * dt
        F[1, 2] = np.sin(theta) * dt

        Q_noise = np.diag([0.1 * dt**2, 0.1 * dt**2, self.Q[2, 2] * dt**2, self.Q[3, 3] * dt**2])
        self.P = F @ self.P @ F.T + Q_noise        #(Belirsizlik) artar

    def update(self, z):       #(Düzelt - GPS ile)
        z_pred = self.H @ self.x
        y = z - z_pred
        S = self.H @ self.P @ self.H.T + self.R
        K = self.P @ self.H.T @ np.linalg.inv(S)     #Benim tahminim mi daha iyi, yoksa GPS mi? (Matrislerin büyüklüğüne göre karar verir)
        self.x = self.x + K @ y                      #self.x (Konum) güncellenir
        self.P = (self.I - K @ self.H) @ self.P      #self.P (Belirsizlik) azalır

# YARDIMCI FONKSİYON -- Bu fonksiyon, GPS'ten gelen Enlem/Boylam farklarını, Dünya yarıçapını ($R = 6371000$ m) kullanarak metre cinsinden X (Doğu) ve Y (Kuzey) mesafesine çevirir.
def latlon_to_xy(lat, lon, lat0, lon0):
    R = 6371000
    d_lat = np.deg2rad(lat - lat0)
    d_lon = np.deg2rad(lon - lon0)
    lat0_rad = np.deg2rad(lat0)
    x = R * d_lon * np.cos(lat0_rad)
    y = R * d_lat
    return x, y

# --- 3. LOG PARSE ETME (VERİ OKUMA) ---
imu_data = []
gps_data = []

# Yüklenen dosyayı bellekten oku
content = uploaded[filename].decode('utf-8').splitlines()

for line in content:
    parts = line.strip().split(',')
    parts = [p.strip() for p in parts]

    if len(parts) < 2: continue

    # GPS VERİSİ (Senin verdiğin FMT satırına göre: Lat->8, Lng->9)  Satır GPS verisi mi?  bunun kontrolünü yapar
    if parts[0] == 'GPS':
        try:
            status = int(parts[3])
            if status >= 3:
                t = float(parts[1])
                lat = float(parts[8])
                lon = float(parts[9])

                # ArduPilot tamsayı düzeltmesi (örn: 390000000 -> 39.0)
                if abs(lat) > 90: lat /= 10000000.0
                if abs(lon) > 180: lon /= 10000000.0

                gps_data.append([t, lat, lon])
        except (ValueError, IndexError):
            pass

    # IMU VERİSİ (Standart ArduPilot: AccX->5, GyrZ->4)    Satır IMU verisi mi?  bunun kontrolünü yapar
    if parts[0] == 'IMU':
        try:
            t = float(parts[1])
            gyr_z = float(parts[4])
            acc_x = float(parts[5])
            imu_data.append([t, acc_x, gyr_z])
        except (ValueError, IndexError):
            pass

print(f"Veri Okundu: {len(imu_data)} IMU satırı, {len(gps_data)} GPS satırı.")

if len(imu_data) == 0 or len(gps_data) == 0:
    print("HATA: Yeterli veri yok. Dosya formatı beklenenden farklı olabilir.")
else:
    # --- 4. SİMÜLASYON ---
    lat0 = gps_data[0][1]
    lon0 = gps_data[0][2]

    # Filtre Ayarları  lat0, lon0 değişkenlerine ilk okunan GPS konumu atanır. Artık her şey bu noktaya göre (0,0) metre olarak hesaplanır.
    ekf = EKF_GNSS_INS(dt=0.02, std_acc=0.5, std_yaw_rate=0.1, std_gps=3.0)   #dt=0.02: Her 0.02 saniyede bir (saniyede 50 kere) hesaplama yapacaksın.
                                                                              #std_acc=0.5: İvmeölçerim biraz titrek çalışıyor, +- 0.5 m/s^2 hata yapabilir. (Bu değeri düşürürsen filtre IMU'ya daha çok güvenir).
                                                                              #std_yaw_rate=0.1: Jiroskopum dönüşlerde +- 0.1 rad/s hata yapabilir.
                                                                              #std_gps=3.0: GPS cihazım çok hassas değil, konumu  +- 3 metre hatalı gösterebilir. (Bu değeri artırırsan filtre GPS'i daha az ciddiye alır, IMU'ya ağırlık verir).
    ekf.x[0, 0] = 0
    ekf.x[1, 0] = 0

    est_path = []
    gps_xy_points = []
    gps_index = 0
    prev_time_us = imu_data[0][0]

    for i in range(len(imu_data)):       #Simülasyonun "kalp atışını" (clock) IMU belirler. Zaman, IMU verisinin zaman damgasına (curr_time_us) göre akar.
        curr_time_us = imu_data[i][0]
        dt = (curr_time_us - prev_time_us) / 1_000_000.0   #Bir önceki ölçümden bu yana kaç saniye geçti?

        if dt <= 0 or dt > 1.0:
            prev_time_us = curr_time_us
            continue

        ekf.dt = dt

        # GİRDİLER (IMU)
        # NOT: Gyro verisi radyan mı derece mi?-- RADYAN

        acc_x = imu_data[i][1]
        yaw_rate = imu_data[i][2] # Radyana çevirdim.

        ekf.predict([acc_x, yaw_rate])

        # DÜZELTME (GPS) Şu anki zamanda elimde bir GPS verisi var mı?        #burda imu ve gps verilerinin zamanları  ayarlanıyor
        if gps_index < len(gps_data):
            gps_t = gps_data[gps_index][0]
            if gps_t <= curr_time_us:
                lat = gps_data[gps_index][1]
                lon = gps_data[gps_index][2]
                xm, ym = latlon_to_xy(lat, lon, lat0, lon0)

                ekf.update(np.array([[xm], [ym]]))
                gps_xy_points.append([xm, ym])
                gps_index += 1

        est_path.append(ekf.x[:2].flatten())
        prev_time_us = curr_time_us

    # --- 5. GÖRSELLEŞTİRME ---
    est_path = np.array(est_path)
    gps_xy_points = np.array(gps_xy_points)

    plt.figure(figsize=(10, 8))
    if len(gps_xy_points) > 0:
        plt.scatter(gps_xy_points[:, 0], gps_xy_points[:, 1], c='r', marker='.', alpha=0.5, label='Ham GPS')
    plt.plot(est_path[:, 0], est_path[:, 1], 'b-', linewidth=2, label='EKF (Füzyon)')

    plt.title('ArduPilot Log Analizi: GPS vs EKF')
    plt.xlabel('Doğu (Metre)')
    plt.ylabel('Kuzey (Metre)')
    plt.legend()
    plt.grid()
    plt.axis('equal')
    plt.show()

import matplotlib.pyplot as plt
import numpy as np
from google.colab import files

print("--- VERİ KONTROL VE ANALİZ ARACI ---")
print("Lütfen .log dosyasını tekrar seçin:")
uploaded = files.upload()
filename = next(iter(uploaded))

print(f"\n'{filename}' dosyası inceleniyor...\n")

# Veri listeleri
raw_gps = []
raw_imu = []

# Dosyayı satır satır oku
content = uploaded[filename].decode('utf-8', errors='ignore').splitlines()

print(f"Toplam Satır Sayısı: {len(content)}")
print("-" * 50)

# İLK 5 SATIRI GÖRMEK İÇİN (Header kontrolü)
print("DOSYANIN İLK 5 SATIRI:")
for i in range(5):
    print(content[i])
print("-" * 50)

# PARSE İŞLEMİ
for line in content:
    parts = line.strip().split(',')
    parts = [p.strip() for p in parts]

    if len(parts) < 2: continue

    # 1. GPS KONTROLÜ
    if parts[0] == 'GPS':
        try:
            # Senin FMT satırına göre: GPS, TimeUS(1), ..., Status(3), ..., Lat(8), Lng(9)
            time_us = float(parts[1])
            status = int(parts[3])
            lat = float(parts[8])
            lon = float(parts[9])
            alt = float(parts[10]) # Altitude genelde 10. sıradadır

            raw_gps.append([time_us, status, lat, lon, alt])
        except Exception as e:
            # Hata olursa o satırı atla ama hatayı bilmek isteyebiliriz
            pass

    # 2. IMU KONTROLÜ
    if parts[0] == 'IMU':
        try:
            # Standart: IMU, TimeUS(1), ..., GyrZ(4), AccX(5)
            time_us = float(parts[1])
            gyr_z = float(parts[4])
            acc_x = float(parts[5])

            raw_imu.append([time_us, acc_x, gyr_z])
        except:
            pass

# --- SONUÇ RAPORU ---
raw_gps = np.array(raw_gps)
raw_imu = np.array(raw_imu)

print(f"\nBULUNAN VERİ ADEDİ:")
print(f"GPS Satırı Sayısı: {len(raw_gps)}")
print(f"IMU Satırı Sayısı: {len(raw_imu)}")

if len(raw_gps) > 0:
    print("\n--- GPS VERİ ÖRNEĞİ (İLK 5 VERİ) ---")
    print("TimeUS | Status | Lat | Lon | Alt")
    print(raw_gps[:5])

    # Koordinat Formatı Kontrolü
    sample_lat = raw_gps[0, 2]
    if abs(sample_lat) > 90:
        print(f"\n[UYARI] Enlem değeri {sample_lat} görünüyor.")
        print("-> Bu veri TAMSAYI (Integer) formatında. 10.000.000'a bölünmesi gerekiyor.")
        raw_gps[:, 2] /= 10000000.0 # Düzeltme
        raw_gps[:, 3] /= 10000000.0
    else:
        print(f"\n[BİLGİ] Enlem değeri {sample_lat} görünüyor. Format ONDALIK (Float).")

if len(raw_imu) > 0:
    print("\n--- IMU VERİ ÖRNEĞİ (İLK 5 VERİ) ---")
    print("TimeUS | AccX | GyrZ")
    print(raw_imu[:5])

print("-" * 50)

# --- GÖRSEL KONTROL (GRAFİKLER) ---
plt.figure(figsize=(12, 10))

# 1. GPS Rotası
plt.subplot(3, 1, 1)
if len(raw_gps) > 0:
    # Status >= 3 olanları (3D Fix) filtrele
    valid_gps = raw_gps[raw_gps[:, 1] >= 3]
    plt.plot(valid_gps[:, 3], valid_gps[:, 2], 'r.')
    plt.title(f'GPS Rotası (Lat vs Lon) - Geçerli Nokta Sayısı: {len(valid_gps)}')
    plt.xlabel('Longitude')
    plt.ylabel('Latitude')
    plt.grid(True)
else:
    plt.title("GPS Verisi Yok!")

# 2. İvme (Acc X)
plt.subplot(3, 1, 2)
if len(raw_imu) > 0:
    plt.plot(raw_imu[:, 0], raw_imu[:, 1], 'b')
    plt.title('IMU İvme (Acc X)')
    plt.ylabel('m/s^2')
    plt.grid(True)

# 3. Dönüş Hızı (Gyro Z)
plt.subplot(3, 1, 3)
if len(raw_imu) > 0:
    plt.plot(raw_imu[:, 0], raw_imu[:, 2], 'g')
    plt.title('IMU Gyro (Gyr Z)')
    plt.ylabel('rad/s')
    plt.xlabel('Zaman (TimeUS)')
    plt.grid(True)

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import io

# --- AYAR KISMI ---
# Hangi GPS adımını incelemek istiyorsun? Buraya yaz.
# Öneri: 10 (Başlangıç), 300 (Orta), 600 (Dönüşler)
DEBUG_STEP = 300
# ------------------

# --- 1. DOSYA YÜKLEME ---
print("Lütfen .log dosyasını seçin:")
uploaded = files.upload()
filename = next(iter(uploaded))
print(f"\n'{filename}' yüklendi, analiz başlıyor...")

# --- 2. EKF SINIFI ---
class EKF_GNSS_INS:
    def __init__(self, dt, std_acc, std_yaw_rate, std_gps):
        self.dt = dt
        self.x = np.zeros((4, 1))
        self.P = np.eye(4)
        self.Q = np.diag([0, 0, std_acc**2, std_yaw_rate**2])
        self.R = np.diag([std_gps**2, std_gps**2])
        self.H = np.array([[1, 0, 0, 0], [0, 1, 0, 0]])
        self.I = np.eye(4)

    def predict(self, u):
        theta = self.x[3, 0]
        v = self.x[2, 0]
        a = u[0]
        omega = u[1]
        dt = self.dt

        new_x = self.x[0, 0] + v * np.cos(theta) * dt
        new_y = self.x[1, 0] + v * np.sin(theta) * dt
        new_v = v + a * dt
        new_theta = theta + omega * dt
        self.x = np.array([[new_x], [new_y], [new_v], [new_theta]])

        F = np.eye(4)
        F[0, 3] = -v * np.sin(theta) * dt
        F[0, 2] = np.cos(theta) * dt
        F[1, 3] = v * np.cos(theta) * dt
        F[1, 2] = np.sin(theta) * dt

        Q_noise = np.diag([0.1 * dt**2, 0.1 * dt**2, self.Q[2, 2] * dt**2, self.Q[3, 3] * dt**2])
        self.P = F @ self.P @ F.T + Q_noise

    def update(self, z, debug=False):
        z_pred = self.H @ self.x
        y = z - z_pred
        S = self.H @ self.P @ self.H.T + self.R
        K = self.P @ self.H.T @ np.linalg.inv(S)

        # --- DEBUG BASKISI ---
        if debug:
            print("\n" + "="*40)
            print(f"--- ADIM DETAYI (GPS Adımı: {DEBUG_STEP}) ---")
            print(f"1. GPS Ölçümü (z) [Metre]:\n{z.T}")
            print(f"2. Tahmin ile Fark (Innovation y):\n{y.T}")
            print(f"3. Kalman Kazancı (K):\n{K}")
            print("-" * 20)

        self.x = self.x + K @ y
        self.P = (self.I - K @ self.H) @ self.P

        if debug:
            print(f"4. GÜNCEL STATE (x) [Sonuç]:\n{self.x.T}")
            print("="*40 + "\n")

def latlon_to_xy(lat, lon, lat0, lon0):
    R = 6371000
    d_lat = np.deg2rad(lat - lat0)
    d_lon = np.deg2rad(lon - lon0)
    lat0_rad = np.deg2rad(lat0)
    x = R * d_lon * np.cos(lat0_rad)
    y = R * d_lat
    return x, y

# --- 3. VERİ OKUMA ---
imu_data = []
gps_data = []
content = uploaded[filename].decode('utf-8', errors='ignore').splitlines()

for line in content:
    parts = line.strip().split(',')
    parts = [p.strip() for p in parts]
    if len(parts) < 2: continue

    if parts[0] == 'GPS':
        try:
            status = int(parts[3])
            if status >= 3:
                t = float(parts[1])
                lat = float(parts[8])
                lon = float(parts[9])
                if abs(lat) > 90: lat /= 10000000.0
                if abs(lon) > 180: lon /= 10000000.0
                gps_data.append([t, lat, lon])
        except: pass

    if parts[0] == 'IMU':
        try:
            t = float(parts[1])
            gyr_z = float(parts[4])
            acc_x = float(parts[5])
            imu_data.append([t, acc_x, gyr_z])
        except: pass

# --- 4. SİMÜLASYON ---
if len(imu_data) > 0 and len(gps_data) > 0:
    lat0, lon0 = gps_data[0][1], gps_data[0][2]
    ekf = EKF_GNSS_INS(dt=0.02, std_acc=0.5, std_yaw_rate=0.1, std_gps=3.0)
    ekf.x[0,0], ekf.x[1,0] = 0, 0

    est_path = []
    gps_xy_points = []
    gps_index = 0
    prev_time_us = imu_data[0][0]

    np.set_printoptions(precision=4, suppress=True)

    print(f"Simülasyon çalışıyor... (GPS Adımı {DEBUG_STEP} bekleniyor)")

    for i in range(len(imu_data)):
        curr_time_us = imu_data[i][0]
        dt = (curr_time_us - prev_time_us) / 1_000_000.0

        if dt <= 0 or dt > 1.0:
            prev_time_us = curr_time_us
            continue

        ekf.dt = dt
        acc_x = imu_data[i][1]
        yaw_rate = imu_data[i][2]

        ekf.predict([acc_x, yaw_rate])

        if gps_index < len(gps_data):
            gps_t = gps_data[gps_index][0]
            if gps_t <= curr_time_us:
                lat, lon = gps_data[gps_index][1], gps_data[gps_index][2]
                xm, ym = latlon_to_xy(lat, lon, lat0, lon0)

                # --- AYARLADIĞIN ADIMI KONTROL EDEN YER ---
                is_debug_step = (gps_index == DEBUG_STEP)

                if is_debug_step:
                     print(f"\n>> GİRİŞ (IMU): İvme={acc_x:.3f} m/s2, Dönüş={yaw_rate:.3f} rad/s")

                ekf.update(np.array([[xm], [ym]]), debug=is_debug_step)

                gps_xy_points.append([xm, ym])
                gps_index += 1

        est_path.append(ekf.x[:2].flatten())
        prev_time_us = curr_time_us

    est_path = np.array(est_path)
    gps_xy_points = np.array(gps_xy_points)

#NOTLAR
# Eğer K 1'e yakınsa: Filtre kendi tahminine güvenmez, GPS verisini olduğu gibi kabul eder.
# Eğer K 0'a yakınsa: Filtre GPS'in hatalı olduğunu düşünür ve kendi tahminine (IMU) sadık kalır."
# std_gps = 3.0 metre dedik (GPS'e güvenme, hatası büyük dedik).
# std_acc = 0.5 dedik (IMU daha güvenilir dedik).

# Kalman kazncı matrixinde satırlar (4 adet): Dronun Durumları (X, Y, Hız, Açı).Sütunlar (2 adet): GPS'ten gelen hatalar (GPS_XHatası, GPS_Y Hatası).


#İnovasyon / Artık Değer (y)
#Kod: y = z - Hx
#Teknik Tanım: Ölçüm Artığı (Measurement Residual). Ölçülen değer ile tahmin edilen değer arasındaki farktır.
#"Filtre kendi hesabına göre bir yer tahmin eder (Predict), GPS ise başka bir yer söyler. İnovasyon, bu ikisi arasındaki farktır. Eğer bu değer 0'a yakınsa filtre ve GPS hemfikirdir."



#Filtre, dronun konumunu GPS'ten 43 cm daha ileride (yaklaşık 131.05 metrede) tahmin etmiş.

# Kalman kazncı matrixinde satırlar (4 adet): Dronun Durumları (X, Y, Hız, Açı).Sütunlar (2 adet): GPS'ten gelen hatalar (GPS_XHatası, GPS_Y Hatası).

#IMU YA DA GPS E GÜVENECEĞİMİ NASIL BİLİRİM?
#Ani Hareketlerde ve Dönüşlerde: IMU'ya güvenmelisin. Çünkü GPS, o keskin dönüşü yakalayamayacak kadar yavaştır.

#Düz Uçuşta ve Konum Doğrulamada: GPS'e güvenmelisin. Çünkü IMU zamanla "kaymaya" (drift) başlar, onu yerine oturtacak olan GPS'tir.


# inavasyon matrixi ile kalman kazncı rasındaki ilişki
# X Konumu İçin Düzeltme (1. Satır)Filtre X konumunu ne kadar kaydıracak?
# Formül:Delta x = (K_{xx} ÇARPI y_x) + (K_{xy} ÇARPI y_y)
# Değerler: (0.076 X -0.436) + (-0.004 X -1.023)
# Hesap: (-0.033) + (0.004) = -0.029 metre
# Yorum:İnovasyon X ekseninde -43 cm idi (GPS "43 cm geridesin" dedi).Filtre bu uyarının sadece -2.9 cm'sini kabul etti.
# Sonuç: Filtre GPS'e %7.6 oranında güvendi (0.076) ve konumunu hafifçe geriye çekti.



#####İDEAL DURUMU BULMAK İÇİN GPS VE IMU GÜVENME ORANLARINI DEĞİŞTİRMEM GEREKİYOR EĞER GPS E ÇOK GÜVENİRSEM ROTA TİTREK OLUR



import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import io

# --- AYAR KISMI ---
# Haritada işaretlemek istediğin adım:
DEBUG_STEP = 600
# ------------------

# --- 1. DOSYA YÜKLEME ---
print("Lütfen .log dosyasını seçin:")
uploaded = files.upload()
filename = next(iter(uploaded))
print(f"\n'{filename}' yüklendi, analiz başlıyor...")

# --- 2. EKF SINIFI ---
class EKF_GNSS_INS:
    def __init__(self, dt, std_acc, std_yaw_rate, std_gps):
        self.dt = dt
        self.x = np.zeros((4, 1))
        self.P = np.eye(4)
        self.Q = np.diag([0, 0, std_acc**2, std_yaw_rate**2])
        self.R = np.diag([std_gps**2, std_gps**2])
        self.H = np.array([[1, 0, 0, 0], [0, 1, 0, 0]])
        self.I = np.eye(4)

    def predict(self, u):
        theta = self.x[3, 0]
        v = self.x[2, 0]
        a = u[0]
        omega = u[1]
        dt = self.dt

        new_x = self.x[0, 0] + v * np.cos(theta) * dt
        new_y = self.x[1, 0] + v * np.sin(theta) * dt
        new_v = v + a * dt
        new_theta = theta + omega * dt
        self.x = np.array([[new_x], [new_y], [new_v], [new_theta]])

        F = np.eye(4)
        F[0, 3] = -v * np.sin(theta) * dt
        F[0, 2] = np.cos(theta) * dt
        F[1, 3] = v * np.cos(theta) * dt
        F[1, 2] = np.sin(theta) * dt

        Q_noise = np.diag([0.1 * dt**2, 0.1 * dt**2, self.Q[2, 2] * dt**2, self.Q[3, 3] * dt**2])  # HIZ GÜRÜLTÜSÜ "std_acc" Q[2, 2]  #AÇI GÜRÜLTÜSÜQ "std_yaw_rate" [3, 3]
        self.P = F @ self.P @ F.T + Q_noise

    def update(self, z, debug=False):
        z_pred = self.H @ self.x
        y = z - z_pred
        S = self.H @ self.P @ self.H.T + self.R
        K = self.P @ self.H.T @ np.linalg.inv(S)

        if debug:
            print("\n" + "="*40)
            print(f"--- ADIM DETAYI (GPS Adımı: {DEBUG_STEP}) ---")
            print(f"1. GPS Ölçümü (z) [Metre]:\n{z.T}")
            print(f"2. Tahmin ile Fark (Innovation y):\n{y.T}")
            print(f"3. Kalman Kazancı (K):\n{K}")
            print("-" * 20)

        self.x = self.x + K @ y
        self.P = (self.I - K @ self.H) @ self.P

        if debug:
            print(f"4. GÜNCEL STATE (x) [Sonuç]:\n{self.x.T}")
            print("="*40 + "\n")

def latlon_to_xy(lat, lon, lat0, lon0):
    R = 6371000
    d_lat = np.deg2rad(lat - lat0)
    d_lon = np.deg2rad(lon - lon0)
    lat0_rad = np.deg2rad(lat0)
    x = R * d_lon * np.cos(lat0_rad)
    y = R * d_lat
    return x, y

# --- 3. VERİ OKUMA ---
imu_data = []
gps_data = []
content = uploaded[filename].decode('utf-8', errors='ignore').splitlines()

for line in content:
    parts = line.strip().split(',')
    parts = [p.strip() for p in parts]
    if len(parts) < 2: continue

    if parts[0] == 'GPS':
        try:
            status = int(parts[3])
            if status >= 3:
                t = float(parts[1])
                lat = float(parts[8])
                lon = float(parts[9])
                if abs(lat) > 90: lat /= 10000000.0
                if abs(lon) > 180: lon /= 10000000.0
                gps_data.append([t, lat, lon])
        except: pass

    if parts[0] == 'IMU':
        try:
            t = float(parts[1])
            gyr_z = float(parts[4])
            acc_x = float(parts[5])
            imu_data.append([t, acc_x, gyr_z])
        except: pass

# --- 4. SİMÜLASYON ---
if len(imu_data) > 0 and len(gps_data) > 0:
    lat0, lon0 = gps_data[0][1], gps_data[0][2]
    ekf = EKF_GNSS_INS(dt=0.02, std_acc=0.5, std_yaw_rate=0.1, std_gps=3.0)    ####### FİLTRE İYİLEŞTİRMESİ İÇİN BU DEĞERLERİ OYNAMALIYIM
    ekf.x[0,0], ekf.x[1,0] = 0, 0

    est_path = []
    gps_xy_points = []
    gps_index = 0
    prev_time_us = imu_data[0][0]

    # *** YENİ: Debug Konumunu Saklamak İçin Değişken ***
    debug_location = None

    np.set_printoptions(precision=4, suppress=True)

    print(f"Simülasyon çalışıyor... (GPS Adımı {DEBUG_STEP} işaretlenecek)")

    for i in range(len(imu_data)):
        curr_time_us = imu_data[i][0]
        dt = (curr_time_us - prev_time_us) / 1_000_000.0

        if dt <= 0 or dt > 1.0:
            prev_time_us = curr_time_us
            continue

        ekf.dt = dt
        acc_x = imu_data[i][1]
        yaw_rate = imu_data[i][2]

        ekf.predict([acc_x, yaw_rate])

        if gps_index < len(gps_data):
            gps_t = gps_data[gps_index][0]
            if gps_t <= curr_time_us:
                lat, lon = gps_data[gps_index][1], gps_data[gps_index][2]
                xm, ym = latlon_to_xy(lat, lon, lat0, lon0)

                is_debug_step = (gps_index == DEBUG_STEP)

                if is_debug_step:
                     print(f"\n>> GİRİŞ (IMU): İvme={acc_x:.3f} m/s2, Dönüş={yaw_rate:.3f} rad/s")

                ekf.update(np.array([[xm], [ym]]), debug=is_debug_step)

                # *** YENİ: Eğer debug adımındaysak, o anki konumu kaydet ***
                if is_debug_step:
                    debug_location = [ekf.x[0,0], ekf.x[1,0]] # [x, y]

                gps_xy_points.append([xm, ym])
                gps_index += 1

        est_path.append(ekf.x[:2].flatten())
        prev_time_us = curr_time_us

    # --- 5. GÖRSELLEŞTİRME ---
    est_path = np.array(est_path)
    gps_xy_points = np.array(gps_xy_points)

    plt.figure(figsize=(12, 10))

    # 1. Tüm GPS Noktaları
    if len(gps_xy_points) > 0:
        plt.scatter(gps_xy_points[:, 0], gps_xy_points[:, 1], c='r', marker='.', alpha=0.3, label='GPS Verisi')

    # 2. EKF Rotası
    plt.plot(est_path[:, 0], est_path[:, 1], 'b-', linewidth=2, label='EKF Rotası')

    # 3. *** YENİ: DEBUG NOKTASINI İŞARETLE ***
    if debug_location is not None:
        plt.scatter(debug_location[0], debug_location[1], c='black', s=300, marker='*', zorder=10, label=f'Debug Adımı ({DEBUG_STEP})')
        # Yanına yazı yazalım
        plt.text(debug_location[0] + 2, debug_location[1], f"  <- ŞU AN BURADAYIZ\n      (Adım {DEBUG_STEP})", fontsize=12, fontweight='bold', color='black')

    plt.title(f'GNSS/INS Entegrasyonu (İncelenen Adım: {DEBUG_STEP})')
    plt.xlabel('Doğu (m)')
    plt.ylabel('Kuzey (m)')
    plt.legend()
    plt.grid()
    plt.axis('equal')
    plt.show()
else:
    print("Veri yok.")

#  DÖNÜŞ NOKTAALRINDAKİ SAVRULMA İÇİN NE YAPABİLRİİM
#std_gps = 1.0 (veya 1.5)   GPS DAHA ÇOK GÜVEN
#std_yaw_rate = 0.5 (veya 0.8) ARTTIRABİLİRİM
#std_acc = 1.0   ARTTIRABİLİRİM